export const OrderActionTypes = {
  SET_CURRENT_ORDER: 'SET_CURRENT_ORDER',
  ADD_ITEM_TO_ORDER: 'ADD_ITEM_TO_ORDER',
  ADD_ITEM_QUANTITY: 'ADD_ITEM_QUANTITY',
  REDUCE_ITEM_QUANTITIY: 'REDUCE_ITEM_QUANTITY',
  DELETE_ITEM: 'DELETE_ITEM'
}